<a href="https://colab.research.google.com/github/MMoronto/pytorch_exercises/blob/master/Pytorch_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **pytorch fundamentals**

In [2]:
import torch
torch.__version__

'1.13.0+cu116'

Creating tensors

In [3]:
# Create a scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# Get the Python number within a one-element tensor
scalar.item()

7

In [6]:
# Create a vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
#check the number of dimensions of vector
vector.ndim

1

In [8]:
# Check shape of vector
vector.shape

torch.Size([2])

In [9]:
# Matrix
matrix = torch.tensor([[7, 8],
                      [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
matrix.ndim

2

In [11]:
matrix.shape

torch.Size([2, 2])

In [12]:
# Let's make a tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [13]:
# Check number of dimensions for TENSOR
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.0599, 0.6462, 0.8035, 0.4620],
         [0.4676, 0.7846, 0.7646, 0.3498],
         [0.8521, 0.5079, 0.5246, 0.2744]]), torch.float32)

In [16]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [17]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]), torch.float32)

In [18]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]), torch.float32)

In [19]:
# Use torch.arange(). 
# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
# Create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [21]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # Defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # Defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [22]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16

In [23]:
# create a tensor and find out details about it
some_tensor = torch.rand(3, 4)

# Find out details about the tensor
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.8149, 0.4463, 0.2585, 0.1338],
        [0.0562, 0.1287, 0.3244, 0.8989],
        [0.2456, 0.2767, 0.1861, 0.8649]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [24]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [25]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

## **Tensor Ops**

In [26]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [27]:
# Multiply it by 10
tensor * 10

tensor([10, 20, 30])

In [28]:
# Tensors don't change unless they are reassigned
tensor

tensor([1, 2, 3])

In [29]:
# Subtract and reassign
tensor = tensor - 10
tensor 

tensor([-9, -8, -7])

In [30]:
# Add and reassign
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [31]:
# Use built-in pytorch functions
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [32]:
# Original tensor is still unchanged
tensor

tensor([1, 2, 3])

In [33]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [34]:
# Element-wise multiplication and matrix multiplication
import torch
tensor = torch.tensor([1, 2, 3])
tensor.shape 

torch.Size([3])

In [35]:
# Element-wise and matrix multiplication
tensor * tensor

tensor([1, 4, 9])

In [36]:
# Matrix multiplicatiion
torch.matmul(tensor, tensor)


tensor(14)

In [37]:
# A not so recommended symbol for matrix multiplication
tensor @ tensor

tensor(14)

In [38]:
%%time
# Matrix multiplication by hand
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 519 µs, sys: 0 ns, total: 519 µs
Wall time: 1.31 ms


tensor(14)

In [39]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 95 µs, sys: 0 ns, total: 95 µs
Wall time: 100 µs


tensor(14)

In [44]:
# # inner dimensions need to match for matrix multiplication to work
# tensor_A = torch.tensor([[1, 2],
#                          [3, 4],
#                          [5, 6]], dtype=torch.float32)

# tensor_B = torch.tensor([[7, 10],
#                          [8, 11],
#                          [9, 12]], dtype=torch.float32)

# torch.matmul(tensor_A, tensor_B) # this won't work because the inner dimensions don't match

In [41]:
# When inner dimensions don't match, you can use the transpose function to enable the multiplication work
print(tensor_A)
print(tensor_B.T)

print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])
Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


In [42]:
# torch.mm is a shortcut for matmul
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [43]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [49]:
# Find max, min, sum, etc. (aggregation)
print(f"Minumum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this gives us an error
print(f"Mean: {x.type(torch.float32).mean()}") # wont work w/o float datatype
print(f"Sum: {x.sum()}")

Minumum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [51]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

In [52]:
#Positional min/max

#create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Return index of max & min vals
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")



Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


In [54]:
# Change tensor datatype

#create a tensor and check its datatype
tensor = torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

In [55]:
# Create a float16 tensor
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [56]:
# Create a int8 tensor
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

In [57]:
# RESHAPING, STACKING, SQUEEZING & UNSQUEEZING

#create a tensor
import torch

x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [59]:
# Let's add an extra dimension w/ torch.reshape()

#Add an extra dimension
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [60]:
# Let's change the view with torch.view()

#Change view (keeps same data as original but changes view)
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [61]:
# Changing z changes x
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [62]:
# Stack tensors on top of each other five times
x_stacked = torch.stack([x, x, x, x], dim=0) # try changing dim to dim=1
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

In [63]:
# try changing dim to dim=1
x_stacked = torch.stack([x, x, x, x], dim=1) 
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.]])

In [64]:
#removing all single dimensions from a tensor

print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Rename extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


In [66]:
# adding a dimension value of 1 at a specific index
# torch.unsqueeze()

print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")


Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
Previous shape: torch.Size([7])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
New shape: torch.Size([1, 7])


In [67]:
# Create tensor w/ specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])
