<a href="https://colab.research.google.com/github/MMoronto/pytorch_exercises/blob/master/Pytorch_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

*pytorch fundamentals

In [2]:
import torch
torch.__version__

'1.13.0+cu116'

Creating tensors

In [3]:
# Create a scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# Get the Python number within a one-element tensor
scalar.item()

7

In [6]:
# Create a vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
#check the number of dimensions of vector
vector.ndim

1

In [8]:
# Check shape of vector
vector.shape

torch.Size([2])

In [9]:
# Matrix
matrix = torch.tensor([[7, 8],
                      [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
matrix.ndim

2

In [12]:
matrix.shape

torch.Size([2, 2])

In [13]:
# Let's make a tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
# Check number of dimensions for TENSOR
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.7544, 0.5886, 0.8323, 0.2615],
         [0.4260, 0.3823, 0.8612, 0.1701],
         [0.3436, 0.5031, 0.8663, 0.8634]]), torch.float32)

In [18]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)