<a href="https://colab.research.google.com/github/MMoronto/pytorch_exercises/blob/master/Pytorch_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **pytorch fundamentals**

In [29]:
import torch
torch.__version__

'1.13.0+cu116'

Creating tensors

In [30]:
# Create a scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [31]:
scalar.ndim

0

In [32]:
# Get the Python number within a one-element tensor
scalar.item()

7

In [33]:
# Create a vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [34]:
#check the number of dimensions of vector
vector.ndim

1

In [35]:
# Check shape of vector
vector.shape

torch.Size([2])

In [36]:
# Matrix
matrix = torch.tensor([[7, 8],
                      [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [37]:
matrix.ndim

2

In [38]:
matrix.shape

torch.Size([2, 2])

In [39]:
# Let's make a tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [40]:
# Check number of dimensions for TENSOR
TENSOR.ndim

3

In [41]:
TENSOR.shape

torch.Size([1, 3, 3])

In [42]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.7494, 0.4951, 0.5371, 0.2412],
         [0.3198, 0.6566, 0.5754, 0.4971],
         [0.9617, 0.6087, 0.2411, 0.0124]]), torch.float32)

In [43]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [44]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]), torch.float32)

In [45]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]), torch.float32)

In [46]:
# Use torch.arange(). 
# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
# Create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [48]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # Defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # Defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [49]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16

In [50]:
# create a tensor and find out details about it
some_tensor = torch.rand(3, 4)

# Find out details about the tensor
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.8571, 0.4865, 0.7944, 0.6576],
        [0.8355, 0.1128, 0.1422, 0.1455],
        [0.0971, 0.6080, 0.6608, 0.6375]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [51]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [52]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

## **Tensor Ops**

In [53]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [54]:
# Multiply it by 10
tensor * 10

tensor([10, 20, 30])

In [55]:
# Tensors don't change unless they are reassigned
tensor

tensor([1, 2, 3])

In [56]:
# Subtract and reassign
tensor = tensor - 10
tensor 

tensor([-9, -8, -7])

In [57]:
# Add and reassign
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [58]:
# Use built-in pytorch functions
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [59]:
# Original tensor is still unchanged
tensor

tensor([1, 2, 3])

In [60]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [61]:
# Element-wise multiplication and matrix multiplication
import torch
tensor = torch.tensor([1, 2, 3])
tensor.shape 

torch.Size([3])

In [62]:
# Element-wise and matrix multiplication
tensor * tensor

tensor([1, 4, 9])

In [63]:
# Matrix multiplicatiion
torch.matmul(tensor, tensor)


tensor(14)

In [64]:
# A not so recommended symbol for matrix multiplication
tensor @ tensor

tensor(14)

In [65]:
%%time
# Matrix multiplication by hand
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 1.28 ms, sys: 37 µs, total: 1.32 ms
Wall time: 2.1 ms


tensor(14)

In [66]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 69 µs, sys: 9 µs, total: 78 µs
Wall time: 82.7 µs


tensor(14)

In [67]:
# inner dimensions need to match for matrix multiplication to work
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # this won't work because the inner dimensions don't match

RuntimeError: ignored

In [ ]:
# When inner dimensions don't match, you can use the transpose function to enable the multiplication work
print(tensor_A)
print(tensor_B.T)

print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

In [ ]:
# torch.mm is a shortcut for matmul
torch.mm(tensor_A, tensor_B.T)

In [ ]:
# This